### ISSUE TITLE
Установка на MacOS

### ISSUE THREAD

**Issue by ghost** [moscow-technologies/ag-blockchain#4]
При вызове "brew install parity --v1.7.9" кусок "--v1.7.9" не распознается и вместо него устанавливается версия Parity 1.8.3-beta

Нужная версия Parity 1.7.9-stable устанавливается при вызове "brew install parity --stable", как рекомендовано на https://github.com/paritytech/homebrew-paritytech/blob/master/README.md

**Comment by smashin** [comment]
Спасибо, вернули в инструкции brew install parity --stable
