### ISSUE TITLE
Идентификатор опроса на АГ

### ISSUE THREAD

**Issue by ghost** [moscow-technologies/ag-blockchain#5]
Как найти идентификатор опроса на АГ?
Перехожу по ссылке на АГ и не вижу ни в списке голосований, ни внутри самих голосований.

**Comment by smashin** [comment]
Добрый день!
Идентификатор доступен в профиле https://ag.mos.ru/profile
по псевдоссылке "Уникальный идентификатор пользователя"

**Comment by ghost** [comment]
Вопрос был про идентификатор ОПРОСА, про который говорится в пункте 9 инструкции по просмотру результатов опроса, а не про идентификатор ПОЛЬЗОВАТЕЛЯ

**Comment by smashin** [comment]
Идентификатор опроса можно увидеть в адресной строке после перехода к опросу, например, https://ag.mos.ru/poll/3242
В данном случае **3242**
В инструкции дописали
