### ISSUE TITLE
Валидация через proof of authority

### ISSUE THREAD

**Issue by egorsmkv** [moscow-technologies/ag-blockchain#7]
Добрый день, @smashin @a-borodenkov 

Недавно прочитал у Григория Бакунова в блоге такой пост:

![addmeto](https://user-images.githubusercontent.com/7875085/33883701-760ca31c-df45-11e7-8c2c-07eb4945d5f9.png)

Можно узнать почему было принято решение использовать именно proof of authority?

**Comment by smashin** [comment]
@egorsmkv, добрый вечер!

Спасибо за вопрос и интерес к проекту, позвольте ответить вам и Григорию.
Изначально для проекта была выбрана цель - реализация приватной блокчейн-сети с возможностью подключения нод-аудиторов для изучения возможностей и ограничений технологии для задач муниципалитета.

Перед непосредственной реализацией мы много экспериментировали и сделали ряд прототипов и исследований производительности, используя разные реализации Ethereum (geth, Parity) и алгоритмы консенсуса (Proof of work, proof of authority) в приватных блокчейн-сетях. С технической точки зрения основной проблемой при реализации проекта была нагрузка, которую создает поток голосов (до нескольких десятков в секунду в пики). При использовании классического алгоритма proof of work возникали проблемы со скоростью записи в блоки этого потока (аналогичные проблемам в глобальной сети Ethereum), майнинг в данном случае достаточно накладен и в принципе для приватных сетей не подходит, поэтому технически обоснован proof of authority.
Вторая причина - интеграция с потоком голосов Активного Гражданина пока не может быть вынесена за внутренний контур ЦОД, голоса пользователей по-прежнему проходят через  серверы приложения, поэтому и запись в блокчейн находится в этом контуре.

Отвечая на вопрос "Зачем?" и опасения по поводу подмены голосов могу сказать:
- Любой пользователь-аудитор может развенуть у себя блокчейн-ноду и в "прямом эфире" следить за поступлением голосов, делать сверку с результатами на ag.mos.ru, видеть что голоса не вычитаются и не меняются
- Переписать блокчейн на компьютере аудитора фактически невозможно
- Аудитор всегда может проверить свой голос по любому из опросов, запросив результат по УИД (который можно посмотреть в профиле на ag.mos.ru/profile)

Ну и, конечно, это только начало, у проекта большие планы развития, сейчас мы активно собираем обратную связь от пользователей и формируем планы по доработкам, поэтому принимается любая конструктивная критика и предложения:)
