### ISSUE TITLE
Why only Owner can vote?

### ISSUE THREAD

**Issue by igorbarinov** [moscow-technologies/ag-blockchain#8]
https://github.com/moscow-technologies/ag-blockchain/blob/8b276de192c839036b966c8473d449d6a203b537/contracts/src/Poll.sol#L106

**Comment by smashin** [comment]
Because all **vote** method calls are made from one blockchain account. 
The reason is peolpe have not blockchain accounts and all the votes pass through the application server. Everyone can check his vote by his token from profile

**Comment by alerdenisov** [comment]
Why not use dapp on ag.mos.ru to sign transaction?

**Comment by kalloc** [comment]
You can easily make periodical database's snapshot with a signature (hash or gpg), why do you use blockchain with only one writer?

**Comment by smashin** [comment]
@alerdenisov dapp will coming soon, this idea is in the process

**Comment by alerdenisov** [comment]
Sounds great! @smashin could you please announce estimate date when it will be released? 

Also, how ag.mos.ru is planning to provide the proof of the fact of granting one and only one key in hands?

**Comment by smashin** [comment]
@alerdenisov next year, 
we have some ideas, I'm not ready to say now:)
